---
abstract: 'Human readable date periods'
author:
  - 'Peter Stuifzand <peter@stuifzand.eu>'
build_requires:
  DateTime::Format::MySQL: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.3, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Period-Human
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Date::Calc: 0
resources:
  bugtracker: https://github.com/pstuifzand/date-period-human/issues
  homepage: https://github.com/pstuifzand/date-period-human
  repository: https://github.com/pstuifzand/date-period-human.git
version: 0.4.4
x_contributors:
  - 'MAJESTIC <majestic@cpan.org>'
  - 'Peter Stuifzand <peter.stuifzand@gmail.com>'
